import Head from "next/head";
import {type NextPage } from "next";
import AdminDashboardLayout from "~/components/layouts/admin-dashboard-layout";

const Analytics: NextPage = () => {
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <AdminDashboardLayout>
            {/* <Courses /> */}
            <div>
              <h1>Analytics</h1>
            </div>
          </AdminDashboardLayout>
        </main>
      </>
    );
  };

  export default Analytics;

