import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { IconSun, IconMoonStars } from "@tabler/icons-react";
import {
  AppShell,
  Navbar,
  Header,
  Footer,
  Aside,
  Text,
  MediaQuery,
  Burger,
  useMantineTheme,
  Group,
  ActionIcon,
  useMantineColorScheme,
  Box,
  rem,
} from "@mantine/core";

const Home: NextPage = () => {
  const theme = useMantineTheme();
  const [opened, setOpened] = useState(false);

  const { colorScheme, toggleColorScheme } = useMantineColorScheme();
  // const dark = colorScheme === 'dark';

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell
          styles={{
            main: {
              background:
                theme.colorScheme === "dark"
                  ? theme.colors.dark[8]
                  : theme.colors.gray[0],
            },
          }}
          navbarOffsetBreakpoint="sm"
          asideOffsetBreakpoint="sm"
          navbar={
            <Navbar height={600} p="xs" width={{ base: 300 }}>
              <Navbar.Section mt="xs">Brand</Navbar.Section>
              <Navbar.Section grow mt="md">
                MainLinks
              </Navbar.Section>
              <Navbar.Section>User</Navbar.Section>
            </Navbar>
          }
          header={
            <Header height={60}>
              <Group sx={{ height: "100%" }} px={20} position="apart">
                Logo
                <ActionIcon
                  variant="default"
                  onClick={() => toggleColorScheme()}
                  size={30}
                >
                  {colorScheme === "dark" ? (
                    <IconSun size="1rem" />
                  ) : (
                    <IconMoonStars size="1rem" />
                  )}
                </ActionIcon>
              </Group>
            </Header>
          }
        >
          <Text>Resize app to see responsive navbar in action</Text>
        </AppShell>{" "}
      </main>
    </>
  );
};

export default Home;
