import { type NextPage } from "next";
import Head from "next/head";
import AdminDashboardLayout from "~/components/layouts/admin-dashboard-layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AdminDashboardLayout>
          {/* <Courses /> */}
          <div>
            <h1>Dashboard</h1>
          </div>
        </AdminDashboardLayout>
      </main>
    </>
  );
};

export default Home;
